import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
const ui = new URL('../../../CodexPlugin~/gameai-track/ui/', import.meta.url);
const result = await build({ entryPoints: [fileURLToPath(new URL('src/main.tsx', ui))], bundle: true, write: false, outfile: 'track.js', format: 'iife', target: 'es2022', jsx: 'automatic', charset: 'utf8', minify: true, legalComments: 'inline', define: { 'process.env.NODE_ENV': '"production"' } });
const template = await readFile(new URL('track.html', ui), 'utf8');
const js = result.outputFiles.find(file => file.path.endsWith('.js')).text;
const css = result.outputFiles.find(file => file.path.endsWith('.css')).text;
const html = template.replace('/* TRACK_BUNDLE */', () => js.replaceAll('</script', '<\\/script')).replace('/* TRACK_STYLES */', () => css);
const output = new URL('../public/', import.meta.url);
await mkdir(output, { recursive: true });
await writeFile(new URL('track.html', output), html);
console.log(`Track UI built: ${Math.round(Buffer.byteLength(html) / 1024)} KiB (uncompressed, self-contained).`);
